#let default-text-size = (default: 14pt, small: 12pt)
#let default-indent = 1.25cm
#let default-margin = (bottom: 20mm, left: 30mm, right: 15mm, top: 20mm)
#let default-justify = true
#let default-leading = 1.5em
#let default-spacing = 1.5em
#let default-figure-margin-bottom = 1.2em
#let default-list-spacing = 1.3em
#let default-enum-spacing = 1.3em
#let default-outline-depth = 3
#let default-heading-margin = (above: 1.5em, below: 1.6em)
